import { Project, SiteSettings } from "./types";

export const DEMO_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Green Valley Premium Plots",
    slug: "green-valley-premium-plots",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=500&fit=crop",
    price: 1500000,
    location: "Avadi, Near Pattabiram",
    city: "Chennai",
    price_min: 1500000,
    price_max: 3500000,
    price_per_sqft: 2500,
    sqft_min: 600,
    sqft_max: 1400,
    facing: ["East", "North", "South"],
    dtcp_approved: true,
    rera_number: "TN/01/Layout/0123/2024",
    status: "new",
    featured: true,
    description: "Green Valley offers DTCP approved premium residential plots in the heart of Avadi. With excellent connectivity to Chennai city, schools, hospitals, and IT corridors, this is the perfect investment for your dream home. All plots come with clear titles and proper documentation.",
    highlights: ["DTCP Approved", "Clear Title", "Gated Community", "24/7 Security", "Underground Drainage", "Wide Roads"],
    amenities: ["Children's Park", "Jogging Track", "Community Hall", "Temple", "Shopping Complex", "Street Lights"],
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
    ],
    video_url: "",
    youtube_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure_url: "/brochure.pdf",
    map_lat: 13.1067,
    map_lng: 80.1006,
    nearby_places: [
      { name: "Avadi Railway Station", distance: "2 km", type: "transport" },
      { name: "AIIMS Hospital", distance: "3 km", type: "hospital" },
      { name: "DAV School", distance: "1 km", type: "school" },
      { name: "Avadi Bus Stand", distance: "1.5 km", type: "transport" },
    ],
    created_at: "2024-01-15",
  },
  {
    id: "2",
    title: "Sunrise Garden Villas & Plots",
    slug: "sunrise-garden-villas",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
    price: 2000000,
    location: "Thiruverkadu, Near Poonamallee",
    city: "Chennai",
    price_min: 2000000,
    price_max: 5000000,
    price_per_sqft: 3200,
    sqft_min: 800,
    sqft_max: 2000,
    facing: ["East", "West", "North"],
    dtcp_approved: true,
    rera_number: "TN/01/Layout/0456/2024",
    status: "hot",
    featured: true,
    description: "Sunrise Garden is a premium gated community offering villa plots with world-class amenities. Located near the IT corridor with excellent connectivity to all parts of Chennai. Enjoy a serene lifestyle surrounded by nature.",
    highlights: ["DTCP Approved", "Bank Loan Available", "Gated Community", "Landscaped Gardens", "Club House", "Swimming Pool"],
    amenities: ["Swimming Pool", "Gym", "Tennis Court", "Community Hall", "Children's Play Area", "Organic Garden"],
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=500&fit=crop",
    ],
    video_url: "",
    youtube_url: "",
    brochure_url: "",
    map_lat: 13.0827,
    map_lng: 80.1139,
    nearby_places: [
      { name: "Poonamallee Junction", distance: "3 km", type: "transport" },
      { name: "Vijaya Hospital", distance: "4 km", type: "hospital" },
      { name: "Velammal School", distance: "2 km", type: "school" },
    ],
    created_at: "2024-02-10",
  },
  {
    id: "3",
    title: "Royal Enclave Residential Plots",
    slug: "royal-enclave-plots",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=500&fit=crop",
    price: 1800000,
    location: "Ambattur, Industrial Estate Road",
    city: "Chennai",
    price_min: 1800000,
    price_max: 4200000,
    price_per_sqft: 2800,
    sqft_min: 600,
    sqft_max: 1500,
    facing: ["South", "East"],
    dtcp_approved: true,
    rera_number: "TN/01/Layout/0789/2024",
    status: "ongoing",
    featured: true,
    description: "Royal Enclave brings you premium residential plots in the rapidly developing Ambattur area. Perfect for both investment and building your dream home. All legal approvals in place.",
    highlights: ["DTCP Approved", "Clear Legal Title", "Ready to Construct", "Tar Roads", "Drainage System", "Electricity"],
    amenities: ["Park", "Shopping Area", "Water Supply", "Street Lights"],
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&h=500&fit=crop",
    ],
    video_url: "",
    youtube_url: "",
    brochure_url: "",
    map_lat: 13.1143,
    map_lng: 80.1548,
    nearby_places: [
      { name: "Ambattur OT", distance: "1 km", type: "transport" },
      { name: "Apollo Hospital", distance: "5 km", type: "hospital" },
      { name: "Sathyabama University", distance: "10 km", type: "school" },
    ],
    created_at: "2024-03-05",
  },
  {
    id: "4",
    title: "Lakeside Paradise Plots",
    slug: "lakeside-paradise-plots",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=500&fit=crop",
    price: 1200000,
    location: "Puzhal, Near Lake",
    city: "Chennai",
    price_min: 1200000,
    price_max: 2800000,
    price_per_sqft: 2200,
    sqft_min: 500,
    sqft_max: 1200,
    facing: ["East", "North", "West"],
    dtcp_approved: true,
    rera_number: "TN/01/Layout/1012/2024",
    status: "new",
    featured: false,
    description: "Live beside the beautiful Puzhal Lake with fresh air and serene surroundings. Lakeside Paradise offers affordable DTCP approved plots with all basic amenities and excellent future appreciation potential.",
    highlights: ["DTCP Approved", "Lake View", "Peaceful Location", "Investment Growth", "Wide Roads", "Water Supply"],
    amenities: ["Lakeside Walking Path", "Garden", "Temple", "Street Lights"],
    images: [
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600566753086-00f18f6b6035?w=800&h=500&fit=crop",
    ],
    video_url: "",
    youtube_url: "",
    brochure_url: "",
    map_lat: 13.1531,
    map_lng: 80.1150,
    nearby_places: [
      { name: "Puzhal Railway Station", distance: "1 km", type: "transport" },
      { name: "Puzhal Lake", distance: "0.5 km", type: "landmark" },
      { name: "Government Hospital", distance: "3 km", type: "hospital" },
    ],
    created_at: "2024-04-01",
  },
  {
    id: "5",
    title: "Metro City Smart Plots",
    slug: "metro-city-smart-plots",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
    price: 2500000,
    location: "Thirumullaivoyal, Near Metro",
    city: "Chennai",
    price_min: 2500000,
    price_max: 6000000,
    price_per_sqft: 3500,
    sqft_min: 700,
    sqft_max: 1800,
    facing: ["East", "South", "North"],
    dtcp_approved: true,
    rera_number: "TN/01/Layout/1345/2024",
    status: "hot",
    featured: true,
    description: "Premium plots near the upcoming metro station! Metro City Smart Plots combines modern urban living with smart investment. Direct connectivity to IT corridors and business hubs makes this the smartest real estate investment in North Chennai.",
    highlights: ["Metro Connectivity", "DTCP Approved", "Smart Infrastructure", "CCTV Surveillance", "Underground Sewage", "Rain Water Harvesting"],
    amenities: ["Co-working Space", "EV Charging", "Smart Play Area", "Shopping Complex", "Health Center"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
    ],
    video_url: "",
    youtube_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure_url: "",
    map_lat: 13.1243,
    map_lng: 80.1321,
    nearby_places: [
      { name: "Thirumullaivoyal Metro", distance: "0.5 km", type: "transport" },
      { name: "Sri Ramachandra Hospital", distance: "4 km", type: "hospital" },
      { name: "CBSE School", distance: "1 km", type: "school" },
    ],
    created_at: "2024-05-15",
  },
  {
    id: "6",
    title: "Heritage Township",
    slug: "heritage-township",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=500&fit=crop",
    price: 900000,
    location: "Avadi, HVF Road",
    city: "Chennai",
    price_min: 900000,
    price_max: 2000000,
    price_per_sqft: 1800,
    sqft_min: 500,
    sqft_max: 1100,
    facing: ["West", "South"],
    dtcp_approved: true,
    rera_number: "TN/01/Layout/1678/2024",
    status: "sold_out",
    featured: false,
    description: "Heritage Township was one of our most popular projects. All plots have been sold. Register your interest for our upcoming projects in the same area.",
    highlights: ["DTCP Approved", "Fully Sold", "Great Location", "All Amenities"],
    amenities: ["Park", "Temple", "Community Hall"],
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=500&fit=crop",
    ],
    video_url: "",
    youtube_url: "",
    brochure_url: "",
    map_lat: 13.1150,
    map_lng: 80.1050,
    nearby_places: [
      { name: "Avadi HVF", distance: "0.5 km", type: "landmark" },
      { name: "Avadi Station", distance: "2 km", type: "transport" },
    ],
    created_at: "2023-06-20",
  },
];

export const DEMO_SETTINGS: SiteSettings = {
  logo_url: "/logo.png",
  favicon_url: "/favicon.ico",
  site_title: "Chennai Housing",
  tagline: "Your Dream Plot Awaits in Chennai",
  phone: "+91 7550177369",
  whatsapp: "917550177369",
  email: "zahidbasha353@gmail.com",
  address: "123, Anna Nagar Main Road, Avadi, Chennai - 600062",
  hero_image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&h=800&fit=crop",
  hero_heading: "Find Your Dream Plot in Chennai",
  hero_subheading: "DTCP Approved Plots in Avadi & Chennai Starting from ₹9 Lakh*",
  primary_color: "#E53935",
  facebook_pixel: "",
  google_analytics: "",
  meta_title: "Chennai Housing - Premium Plots in Avadi & Chennai",
  meta_description: "Find DTCP approved plots and residential properties in Avadi, Chennai. Best prices, legal verification, and easy EMI options.",
};

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Rajesh Kumar",
    location: "Avadi",
    rating: 5,
    text: "Excellent experience buying a plot from Chennai Housing. The documentation was transparent and the team was very professional. My family is very happy with our new plot!",
    avatar: "RK",
  },
  {
    id: "2",
    name: "Priya Shankar",
    location: "Ambattur",
    rating: 5,
    text: "I was looking for DTCP approved plots for months. Chennai Housing made the entire process smooth and hassle-free. Highly recommended for anyone looking to invest in Chennai real estate.",
    avatar: "PS",
  },
  {
    id: "3",
    name: "Mohammed Irfan",
    location: "Thirumullaivoyal",
    rating: 4,
    text: "Great location, good amenities, and fair pricing. The team helped me with bank loan processing too. Very satisfied with my purchase at Metro City Smart Plots.",
    avatar: "MI",
  },
  {
    id: "4",
    name: "Lakshmi Narayanan",
    location: "Poonamallee",
    rating: 5,
    text: "We bought a villa plot at Sunrise Garden and couldn't be happier. The gated community, landscaping, and facilities are top-notch. Worth every rupee!",
    avatar: "LN",
  },
];
